#Ansible Module Name -- oss.py
#Test Case : create bucket with alias
#Ansible Playbook created by - Abha H
---
- name: create bucket with alias
  hosts: localhost
  connection: local
  vars_files:
     - ../../../vars/alicloud-creds.yml
     - ../../vars/test-environment.yml
     - ../../vars/general-parameters.yml
   
  tasks:

   - pause:
       minutes: 1

   - block:
     - name: Scenario 1 - create bucket with alias
       oss:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         #ecs_access_key: '{{ aliyun_acs_access_key }}'
         ecs_secret_key: '{{ aliyun_acs_secret_access_key }}'
         #secret_key: '{{ aliyun_acs_secret_access_key }}'
         mode: '{{ modeCreate }}'
         bucket_name: '{{ bucketName }}'
         #name: '{{ bucketName }}'
         permission: '{{ permission }}'
         region: '{{ region }}'
       register: result_scn1
     - debug: var=result_scn1
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

   - pause:
        minutes: 1

   - block:
     - name: Scenario 2 - Delete bucket with all parameters
       oss:
         acs_access_key: '{{ aliyun_acs_access_key }}'
         acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
         mode: '{{ modeDelete }}'
         region: '{{ region }}'
         bucket: '{{ bucketName }}' # Need to add bucket name of result_scn1
       register: result_del_scn2
     - debug: var=result_del_scn2
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

     always:
      - assert:  
         that:
            - "'failed' not in result_scn1"
            - "'failed' not in result_del_scn2"
         msg: 'Test pass FAILED !!!
               SUCCESS - EXPECTED
               Playbook FAILED due to improper input values.
               REASON: {{ result_scn1}}'
               
