#Ansible Module Name - ECS
#Test Case 3 : Verify the playbook throwing an error when user is trying to remove Security Group from the INVALID ECS Instance
#Ansible Playbook created by - Jogesh N
---
- name: Remove a Security Group from INVALID ECS Instance
  hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml
  
  tasks:
   - block: 
     - name: Remove a Security Group from Existing INVALID ECS Instance
       ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        group_id: '{{ sgGroup }}' #  Security Group
        instance_ids: '{{ removeWindowsInstanceId }}'# INVALID ECS Instance Id
        sg_action: '{{ sgActionLeave }}'


       register: result
     - debug: var=result
     
     rescue:
      - fail:
          msg: "The fail block is added just to handle exception. This block won't be executed ever."
        when: no

     always:
      - assert:  
         that:
            - "result.changed ==  false"
            -  "'Error MessageThe InstanceId provided does not exist in our records.' in result.msg"
         msg: 'Test pass PASSED !!!
               This is a NEGATIVE playbook !!!
               FAILURE - EXPECTED
               REASON: {{ result}}'