# Ansible Module Name - ECS
# Interface : CreateInstance
# Playbook Contains Test-Cases for count parameter
# Playbook created by : Sachin J

- name: Validating count parameter
  hosts: localhost
  connection: local

  vars_files:
  
    - ../vars/test-environment.yml
    - ../vars/general-parameters.yml
    - ../../../vars/alicloud-creds.yml

#count100: 100              It is not feasible to test this Scenario,So we believe on API for this Scenario.

#countInvalid: 102      It is not feasible to test this Scenario,So we believe on API for this Scenario.
            
  tasks:
  
  # Task :1
  
  - block:
    - name: Validating - Valid Count Parameter Which Accepts Value As 2
      ecs:
        acs_access_key: '{{ aliyun_acs_access_key }}'
        acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
        region: '{{ region }}'
        zone: '{{ zone }}'
        image_id: '{{ windowsImageId }}'
        instance_type: '{{ instanceType }}'
        instance_name: '{{ instanceName }}'
        description: '{{ description }}'
        host_name: '{{ host_name }}'
        password: '{{ password }}'
        count: '{{ count }}'
        state: '{{ state }}'
      register: create_instance_result
    - debug: var=create_instance_result

    rescue:
    - fail:
        msg: "The fail block is added just to handle exception. This block won't be executed ever."
      when: no
      
   

    always:
    - assert:
        that:
           - "'failed' not in create_instance_result"
        msg: 'Test pass FAILED !!!'

  - pause: 
       seconds: 15
       
  post_tasks:
   - name: Deleting newly created instance
     ecs:
       acs_access_key: '{{ aliyun_acs_access_key }}'
       acs_secret_access_key: '{{ aliyun_acs_secret_access_key }}'
       region: '{{ region }}'
       instance_id: '{{ create_instance_result.result[0].instance_id }}'
       status: absent
     when:
        - "'failed' not in create_instance_result"